### ISSUE TITLE
proxy: add routes actions

### ISSUE THREAD

**Issue by Amygos** [nethesis/ns8-nethvoice#79]
Every time a new instance of `netvoice` module is created, the instance must register itself on the nethvoce proxy of the node.
The registration is represented as a `route', a route is defined via a JSON object:
```json
{
  "domain": "voice.nethserver.org",
  "address": [
    {
      "uri": "sip:127.0.0.1:5080",
      "description": " module1"
    },
    {
      "uri": "sip:127.0.0.1:5081",
      "description": "module2"
    }
  ]
}
```
where: 
* `domain`: is the fqdn for which the proxy will be responsible for the correct routing.
* `address:` is a list of NethVoice modules that are present on the node.

The registration process is handled by the routes actions of the proxy module.

Steps:
- [x] nethesis/ns8-nethvoice-proxy#2 
- [x] nethesis/ns8-nethvoice-proxy#3 
- [x] nethesis/ns8-nethvoice-proxy#4 

Documentation:
https://www.kamailio.org/docs/modules/5.6.x/modules/domain.html
https://kamailio.org/docs/db-tables/kamailio-db-5.6.x.html#idm2077
https://www.kamailio.org/docs/modules/5.6.x/modules/dialplan.html
https://kamailio.org/docs/db-tables/kamailio-db-5.6.x.html#gen-db-dialplan
https://www.kamailio.org/docs/modules/5.6.x/modules/dispatcher.html
https://kamailio.org/docs/db-tables/kamailio-db-5.6.x.html#idm1959
https://kamailio.org/docs/modules/5.6.x/modules/tls.html
